### ISSUE TITLE
Non-working GPU example in readme

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#5]
```bash
./mdtwObj -t SUBSEQ_SEARCH -i GPU 3 512 0 -f data/subseq_search/T_series data/subseq_search/Q_series \
     -o 3907 421 -m 1 DTW -d 0 2>&1 | tee subseq_search_GPU.txt
```

Output: 
[subseq_search_GPU.txt](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2573782/subseq_search_GPU.txt)

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
I've run the following test example and it works fine with the GPU i've used for testing the software. It might be a problem related either to the GPU device or to the CUDA version you used. I've attached here the [output](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2575973/subseq_search_GPU.txt) running of my GPU. 

Anyway, I removed an extra `/` on the README file that caused the software to stop on that example test due to the wrong following path (/data/subseq_search/Q_series).
